FROM tomcat:8.0
WORKDIR /usr/local/tomcat/webapps
RUN wget https://cgsrv1.arrc.csiro.au/swrepo/PidService/jenkins/trunk/pidsvc-latest.war
RUN mv pidsvc-latest.war pidsvc.war
WORKDIR /usr/local/tomcat/conf
COPY ./context.xml .
COPY ./postgresql-9.4-1202.jdbc41.jar /usr/local/tomcat/lib
ENV TOMCAT_HOME=/usr/local/tomcat/  
ENV HOSTNAME=localhost 
ENV DEPLOYMENT_DIR=/usr/local/ 
ENV PIDSVC_HOME=%TOMCAT_HOME%/webapps/pidsvc/ 
