FROM postgres:latest
RUN mkdir -p /docker-entrypoint-initdb.d 
RUN apt-get update
RUN apt-get install -y wget
COPY ./postresql.sql /docker-entrypoint-initdb.d/
COPY ./postgres-init.sh /docker-entrypoint-initdb.d/
