version: '2.1'
services:
  pg-0:
    image: ksonda/bitnamipg:11
    ports:
      - 5432
    restart: always
    volumes:
      - pg_0_data:/bitnami/postgresql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: ksonda/bitnamipg:11
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    restart: always  
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  pgpool:
    image: docker.io/bitnami/pgpool:4-debian-10
    ports:
      - 5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=custompassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=customuser
      - PGPOOL_POSTGRES_PASSWORD=custompassword
      - PGPOOL_ADMIN_USERNAME=customuser
      - PGPOOL_ADMIN_PASSWORD=custompassword
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_NUM_INIT_CHILDREN=100
      - PGPOOL_MAX_POOL=100
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
  pidsvc-master:
      build:
          context: .
          dockerfile: Dockerfile-pidsvcMaster
      depends_on:
          - pgpool
      expose:
          - "8080"
          - "8009"
      restart: always    
  apache-master:
      build:
          context: .
          dockerfile: Dockerfile-ApacheMaster
      depends_on:
          - pidsvc-master
      ports:
          - "9000:80"
      restart: always        
      
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
