FROM postgres:11
RUN mkdir -p /docker-entrypoint-initdb.d 
RUN apt-get update
RUN apt-get install -y wget
RUN wget https://raw.githubusercontent.com/internetofwater/IoW-PIDsvc/master/PIDsvc/postgresql.sql
COPY ./postgres-init.sh /docker-entrypoint-initdb.d/
