version: '3'
services:
        postgres:
            build:
                context: .
                dockerfile: Dockerfile-PostgreSQL
            volumes:
                - /srv/pid/data/PIDsvc/:/var/lib/postgresql/data
        tomcat3:
            build:
                context: .
                dockerfile: Dockerfile-Tomcat
            depends_on:
                - postgres
            expose:
                - "8080"
                - "8009"
        apache:
            build:
                context: .
                dockerfile: Dockerfile-Apache
            depends_on:
                - tomcat3
            ports:
                - "8095:80"
